### ISSUE TITLE
WALTer and PyCharm 

### ISSUE THREAD

**Issue by bilalderouich** [openalea-incubator/WALTer#53]
From python or terminal, walter.lpy works but launched from pycharm, there are errors.

**Comment by christian34** [comment]
Can you be a bit more specific (which commands do you try )?

**Comment by bilalderouich** [comment]
when we try to execute all the tests (together or in parts), we can see 2 error message : 
"Canestra was not found" and "global name error : exit". But only when we do that with Pycharm, when we execute that in terminal there is no problems

**Comment by christian34** [comment]
After a new run of python setup.py develop for walter, I loose my working configuration: I have now Pycharm in the same state as yours. The problem is that the path to envs\my_env\Scripts is not passed to the process launching the python console, wheareas the path to envs\my_env\Library\bin is passed.
May be a regular conda install of walter will solve this ?

**Comment by bilalderouich** [comment]
Last time, to solve my problems, I had to restart the system, and the whole configuration was updated.
So, I don't know but you can try and check if the openalea environnement is activate

**Comment by christian34** [comment]
The problem for me was because I forget to pass CONDA_PREFIX while running setup.py. 
with:
`python setup.py develop --prefix=%CONDA_PREFIX%`
everything goes fine
