### ISSUE TITLE
Parameter screen resolution caribu

### ISSUE THREAD

**Issue by Emblanc** [openalea-incubator/WALTer#61]

**Comment by Emblanc** [comment]
I will mainly be working on simulations with about 100 plants, . Here are the parameters to run such a simulation, they should be used to set the screen resolution in caribu : 
[sim_scheme_test_screen_resolution.csv.zip](https://github.com/openalea-incubator/WALTer/files/2424641/sim_scheme_test_screen_resolution.csv.zip)

**Comment by christian34** [comment]
I made some tests using branch #64 : 
- I think screen_size =2000 (instead of caribu default 1536) is okay for running the reference simulation with 4 plants (diagonal of the scene bounding box ~1m - because of plant height). The diagonal on the soil bounding domain beeing 0.44 (plants + row)
 - For the simulation with 100 plants, dimention of the diagonal on the soil bounding domain will be increased by 0.85 cm, with plant height unchanged, which yield a screen_size=3100 for these simulations

@Emblanc : may be you could check whether increasing screen_size parameter from 1536 (current value used) to 2000 (for 4 plants defined in sim_scheme_test.csv) or 3100 (for sim_scheme_test_screen_resolution.csv) yield any change in your simulation ?

**Comment by Emblanc** [comment]
This issue was solved by PR #64
